### ISSUE TITLE
Support ruby-mode

### ISSUE THREAD

**Issue by dgutov** [ankurdave/color-identifiers-mode#1]
The following works reasonably well for me:

```
(add-to-list
 'color-identifiers:modes-alist
 `(ruby-mode . ("[^.][[:space:]]*" "\\_<\\([a-zA-Z_$]\\(?:\\s_\\|\\sw\\)*\\)" (nil))))
```

But it still leaves a problem: in Ruby, it's often impossible to distinguish a local variable from a method called without arguments. Can we add some parameter that would allow to pass a function, which would look at the first occurrence of an identifier (inside a given defun, or globally), and tell if it's a variable?

For example, in ruby-mode, that function would check whether the identifier is followed by `=`, or whether it's in a method arguments list.

**Comment by ankurdave** [comment]
Closing since the main issue is resolved. Scoped identifiers can be discussed in new issues/PRs if there is interest.
