### ISSUE TITLE
Colorize lazily

### ISSUE THREAD

**Issue by tigerhawkvok** [ankurdave/color-identifiers-mode#22]
For large files, this mode can significantly slow down opening.

If possible (I'm not familiar enough to say) perhaps defer the colorizing until after the file has loaded?

**Comment by roobie** [comment]
When I use this mode, I can see that big buffers takes a little while longer to open, and when they've opened, the variable names are coloured. However, after some additional time, I can see that all the variable names get new colours for a second time. I'm not sure whether it's connected with this issue, but I thought that creating a new one was a bad idea.

**Comment by 11111000000** [comment]
same here, and I see that issue in other reports
