### ISSUE TITLE
emacs 24.4 on cygwin - (wrong-type-argument listp :pcase--succeed)

### ISSUE THREAD

**Issue by joefromct** [ankurdave/color-identifiers-mode#23]
Hi, 

For some reason i'm getting an error when trying to activate `(color-identifiers-mode)` in an emacs lisp file with emacs 24.4 compiled over cygwin (shouldn't be an issue i don't think?).  The error reported is   `pcase--app-subst-match(:pcase--succeed sexp car x)`. 

I'm not really sure where to start debugging something such as this so let me know what additional information i can provide.  The _Backtrace_ buffer in emacs shows something along these lines... i had trouble pasting everything into the issue as it had non-printable chars/etc.  

```
Debugger entered--Lisp error: (wrong-type-argument listp :pcase--succeed)
pcase--app-subst-match(:pcase--succeed sexp car x)
#[257 "\303@\300\301\302$AB\207" [sexp car x pcase--app-subst-match] 6 "\n\n(fn BRANCH)"]    
((:pcase--succeed #[257 "\302\301\242>\204
 pcase--app-subst-rest((((and (match sexp app car (quote let*)) (match sexp app cdr rest)) #[257 "\302\301\242>\204
 pcase--app-subst-rest((((and (match sexp app car (quote let*)) (match sexp app cdr rest)) #[257 "\302\301\242>\204
pcase--u1(((match sexp app car (quote let)) (match sexp app cdr rest)) #[257 "\302\301\242>\204
```

**Comment by ankurdave** [comment]
This bug probably still exists. If someone has an example of code that triggers it, that would be helpful in fixing it.

**Comment by Hi-Angel** [comment]
Can you please retest it with latest color-identifiers? I wonder if it's still a problem.

As a side note, I'm also using both color-identifiers and smartparens, but not in Cygwin though.

**Comment by Hi-Angel** [comment]
Actually, I just realized [I did some fixes to this code](https://github.com/ankurdave/color-identifiers-mode/pull/69), suggested by byte-compiler in warnings in 2020. Since we never were given a reproducer and the author doesn't answer whether they still see it, I think we can assume it's fixed.

Please feel free to reopen if you see that again.
