### ISSUE TITLE
Stops emacs from opening files

### ISSUE THREAD

**Issue by tigerhawkvok** [ankurdave/color-identifiers-mode#31]
Get this error:

![image](https://cloud.githubusercontent.com/assets/165937/7951427/ff56013a-095b-11e5-9a86-70b8c60d59b1.png)

Had to delete the `.elc` and manually overwrite with the version at daeaf83c3bb4858203c2be0f77a9ea4c006efeef

**Comment by ankurdave** [comment]
I think this should be fixed by e35ee05588d84517193db07d94ce7f29ace10ef6?

**Comment by tigerhawkvok** [comment]
Hm, seems so -- apparently I grabbed package updates at JUST the wrong time!
