### ISSUE TITLE
Add MELPA stable release

### ISSUE THREAD

**Issue by wtfleming** [ankurdave/color-identifiers-mode#33]
MELPA creates a new release every time a commit is pushed to github. Would it be possible to push a version of this to MELPA stable as well?
https://stable.melpa.org
https://github.com/milkypostman/melpa#stable-packages

The instructions I see in this issue
https://github.com/kai2nenobu/guide-key/issues/28

suggest that it is just a matter of a git tag with a version number and commit and git push

cheers

**Comment by ankurdave** [comment]
Thanks. I created a tag v1.0.0.
