### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by yamafaktory** [ankurdave/color-identifiers-mode#38]
Hi,

First of all thanks a lot for your awesome work! I am using this mode on daily basis and it's like getting grapheme-color synaesthesia super powers!

Do you plan to merge the pending pull-request, especially #35? Are you willing to keep maintaining this project?

Thanks!

**Comment by yamafaktory** [comment]
Thanks a lot @ankurdave! I'm closing this one as it has been merged now :+1:

**Comment by ankurdave** [comment]
Thanks for the reminder!
