### ISSUE TITLE
Function `color-identifiers:color-identifier` returns wrong when `identifier` not present in `color-identifiers:color-index-for-identifier`

### ISSUE THREAD

**Issue by galeo** [ankurdave/color-identifiers-mode#44]
As the doc string described, the function `color-identifiers:color-identifier` should return a hex color. However, when the parameter `identifier` not present in `color-identifiers:color-index-for-identifier` it would return wrong value.

```emacs-lisp
    (let ((entry (assoc-string identifier color-identifiers:color-index-for-identifier)))
      (if entry
          (nth (cdr entry) color-identifiers:colors)
        ;; If not present, make a temporary color using the rotating index
        (push (cons identifier (% color-identifiers:current-index
                                  (length color-identifiers:colors)))
              color-identifiers:color-index-for-identifier)
        (setq color-identifiers:current-index
              (1+ color-identifiers:current-index))))))
```

**Comment by ankurdave** [comment]
Hmm, that function is kind of a mess. The else clause is dead code, since we just checked that `identifier` is in `color-identifiers:identifiers`, implying it must also be in `color-identifiers:color-index-for-identifier`. I'm also not sure why both those variables exist when only the latter is needed.

I actually don't like the behavior described in the docstring, because it means that when you're typing a new identifier, it rotates through the set of colors with each new character. I'll change the code and docstring accordingly.

**Comment by galeo** [comment]
```emacs-lisp
(defun color-identifiers:colorize (limit)
  (color-identifiers:scan-identifiers
   (lambda (start end)
     (let* ((identifier (buffer-substring-no-properties start end))
            (hex (color-identifiers:color-identifier identifier)))
       (when hex
         (put-text-property start end 'face `(:foreground ,hex))
         (put-text-property start end 'color-identifiers:fontified t))))
   limit))
```

`hex` returned by `color-identifiers:color-identifier` in `color-identifiers:colorize` may not be `nil`, then ```(put-text-property start end 'face `(:foreground ,hex))``` would be `(:foreground an-int-value)` which is a bad face that leads to other errors. Here is a backtrace log when exporting html in an org mode buffer which contains src block.

```
Debugger entered--Lisp error: (wrong-type-argument stringp 1)
  string-match("\\`#" 1)
  htmlize-color-to-rgb(1)
  htmlize-face-set-from-keyword-attr([cl-struct-htmlize-fstruct nil nil nil nil nil nil nil nil nil] :foreground 1)
  htmlize-attrlist-to-fstruct((:foreground 1))
  htmlize-make-face-map((default (:foreground "#af8eff") underline bold (:foreground 1) font-lock-comment-delimiter-face font-lock-comment-face))
  htmlize-buffer-1()
  htmlize-region(1 49)
  org-html-htmlize-region-for-paste(1 49)
  org-html-fontify-code("{# templates/index.html #}\n<h1>Hello World!</h1>" "jinja2")
... ...
```

`(:foreground 1)` face causes wrong type argument error.

**Comment by ankurdave** [comment]
Does that still happen after the latest commit?

**Comment by galeo** [comment]
It works OK now. Thanks!
