### ISSUE TITLE
[regression] [bisected] parse hangs for indefinite amount of time

### ISSUE THREAD

**Issue by Hi-Angel** [ankurdave/color-identifiers-mode#45]
For opening a `.c` file the color-identifiers-mode probably tries to parse everything at once, which causes Emacs to hang for at least a minute with 100% CPU load and still cursor.

Steps to reprodice:

1. Enable `(global-color-identifiers-mode)`
2. Open [this file](https://github.com/mesa3d/mesa/blob/master/src/gallium/drivers/r600/r600_shader.c)

The commit:

```
Author: Ankur Dave <ankurdave@gmail.com>
Date:   Thu Jun 15 13:38:13 2017 -0700

    When using font-lock for detection, ensure whole buffer is fontified
```

**Comment by Hi-Angel** [comment]
Yesterday I noticed that it actually works just great on small files. I am unfortunately not very good a ELISP, but may be shall there be some kind of check for line numbers, or for the time parse took; or perhaps there's a make a hook to Emacs idle time *(if such exist)*?

**Comment by Hi-Angel** [comment]
Note, it would improve not only the experience with big files, but also experience with weak systems.

**Comment by Hi-Angel** [comment]
I noticed it causes problems with small files too. Even if delay small, like a second or two, because of the [bug reported in this comment](https://github.com/ankurdave/color-identifiers-mode/issues/22#issuecomment-69896023) by @roobie it tries to recolor everything not only for every change, but even if you just scroll the code. Which leads to Emacs freezes every 25-30 seconds.

**Comment by Hi-Angel** [comment]
Interestingly, I am not sure, but looks like with [this PR](https://github.com/ankurdave/color-identifiers-mode/pull/46) mentioned freezes in small files disappeared. I think it's because Emacs does not refontify previosly fontified text, i.e. it now have less work to do.

**Comment by ankurdave** [comment]
Thanks. Until a better solution comes along, I reverted the offending commit.
