### ISSUE TITLE
font-lock-ensure not defined in emacs 24

### ISSUE THREAD

**Issue by finiteprods** [ankurdave/color-identifiers-mode#47]
[Recent commit](https://github.com/ankurdave/color-identifiers-mode/commit/d57e162c2dcb926291ded21cbe46b98ad0ca32c8#diff-aba896d594d5d3c74ea016f325ad2fc9) uses `font-lock-ensure` which I believe is new in emacs 25 thus [breaking users on emacs 24](https://github.com/syl20bnr/spacemacs/issues/9254#issuecomment-317097246).

**Comment by ankurdave** [comment]
Oops, thanks a lot for reporting this. I reverted the commit.
