### ISSUE TITLE
`color-identifiers:regenerate-colors' somehow end up with a negative number

### ISSUE THREAD

**Issue by terlar** [ankurdave/color-identifiers-mode#55]
Somehow recently this mode has started to fail due to the `color-identifiers:regenerate-colors` function generating a green value with a negative number. Any idea what could be causing this?

```
Debugger entered--Lisp error: (overflow-error -3.9467358500864416)
  format("#%04x%04x%04x" 45874.674699756506 -3.9467358500864416 39321.02887623094)
  color-rgb-to-hex(0.7000026657474099 -6.0223328756945775e-05 0.6000004406230403)
  apply(color-rgb-to-hex (0.7000026657474099 -6.0223328756945775e-05 0.6000004406230403))
  #f(compiled-function (lab) #<bytecode 0x43d7db25>)((40.93880504473374 71.59131282262898 -33.59948996162703))
  mapcar(#f(compiled-function (lab) #<bytecode 0x43d7db25>) ((55.969850095011296 -46.000507436863344 19.62744792501374) (37.92861196982004 0.001649772411432826 -0.0023626805090937175) (40.93880504473374 71.59131282262898 -33.59948996162703) (63.951474742506235 -60.79630657802959 64.34808917048707) (35.8910784765621 14.86558451596301 -8.575118569885687) (42.36192063640289 4.958390126570233 -47.41772030495586) (63.59678689625561 -3.1552419727832737 67.26118832479327) (44.52512917499077 -23.365784790247535 24.165666422961053) (36.98022704672353 61.28754873290543 51.3693598087128) (23.463354969597376 61.524269701778486 -78.28325538202843)))
  -map(#f(compiled-function (lab) #<bytecode 0x43d7db25>) ((55.969850095011296 -46.000507436863344 19.62744792501374) (37.92861196982004 0.001649772411432826 -0.0023626805090937175) (40.93880504473374 71.59131282262898 -33.59948996162703) (63.951474742506235 -60.79630657802959 64.34808917048707) (35.8910784765621 14.86558451596301 -8.575118569885687) (42.36192063640289 4.958390126570233 -47.41772030495586) (63.59678689625561 -3.1552419727832737 67.26118832479327) (44.52512917499077 -23.365784790247535 24.165666422961053) (36.98022704672353 61.28754873290543 51.3693598087128) (23.463354969597376 61.524269701778486 -78.28325538202843)))
  color-identifiers:regenerate-colors()
  color-identifiers-mode(toggle)
  funcall-interactively(color-identifiers-mode toggle)
  call-interactively(color-identifiers-mode record nil)
  command-execute(color-identifiers-mode record)
  #f(compiled-function (cmd) #<bytecode 0x431f6165>)("color-identifiers-mode")
```

**Comment by Hi-Angel** [comment]
Oh, I vaguely remember seeing this. Do you use emacs-git? I think it's some bug in git version, but I didn't have time to figure if it's true, and what could be causing it, so I simply have built the git version that works *(4d2f388ae52)*.

**Comment by terlar** [comment]
@Hi-Angel Thanks, yes, I just recently switched to the using a git version of emacs. I guess I should have suspected that, but it is kind of a weird error. I will try a different version to see if that mitigates the problem.

**Comment by jpcima** [comment]
Hi. I have the same problem, and retested with latest git.
On older emacs `(format "%04x")` will accept any integer or real of any sign.
New emacs stops accepting negative reals, but is still happy with negative integers curiously.

**Comment by Hi-Angel** [comment]
@jpcima then it indeed sounds like a bug in Emacs *(like, what's the point of accepting negative reals but not integers?)*. If you want to help, you could try bisecting it, and [reporting to Emacs](https://debbugs.gnu.org/Emacs.html) — I just don't really have time or motivation ATM. A commit that's known to be working is *4d2f388ae52, `; * etc/NEWS: Fix entry about 'electric-quote-replace-double'.`*. I think it broke somewhere in a range of 50 commits afterwards.

**Comment by jpcima** [comment]
On new Emacs it produces "arithmetic error", and on previous ones it produces strange behavior.
Look at this example: a real get truncated if it's in the positives, otherwise it gives 0.

`(format "#%04x #%04x #%04x #%04x" 3 3.14 -3 -3.14)`
`#0003 #0003 #3ffffffffffffffd #0000`

It doesn't make sense either way. In my point of view, the best course of action is just not to pass negatives to %x. cf. pull request above, and use of `color-clamp`

**Comment by terlar** [comment]
Thanks, I tried updating my emacs version with the new package version and that seemed to do the trick.
