### ISSUE TITLE
Typescript variables

### ISSUE THREAD

**Issue by dchrzanowski** [ankurdave/color-identifiers-mode#57]
It would be absolutely fantastic if Typescript would be added.
Just food for thought.

**Comment by Grimscythe1983** [comment]
It in fact was as easy as that. However, it does not colour parameter of function/methods.

**Comment by Grimscythe1983** [comment]
variables are correctly set with a `font-lock-variable-name-face`, but function parameters are just `default`. So I guess that modifying the original `typescript-mode` is a better option.

I have noticed that python's function parameters are also `default`, so it seems that `color-identifiers-mode` has its own logic to highlight theses appropriately.

**Comment by Hi-Angel** [comment]
> I have noticed that python's function parameters are also `default`, so it seems that `color-identifiers-mode` has its own logic to highlight theses appropriately.

Well, yeah, I vaguelly remember seeing lang-specific regexps in the code, I do think @ankurdave *(the maintainer)* will accept a PR if someone would add rules for typescript too. It's just that I don't think it's a proper solution, but oh, well.

**Comment by VizorKit** [comment]
I'm seeing functions in typescript-mode listed as function-name now. Could we add typescript support?

**Comment by ankurdave** [comment]
As @Hi-Angel said, PRs are welcome :)

**Comment by VizorKit** [comment]
@ankurdave hi. I seem to have this issue. I'm not sure if I need to be added to a list, or if I am not following a branching strategy, but I get this issue.
![image](https://user-images.githubusercontent.com/57162749/97595469-b6c2a180-19d1-11eb-9a70-607fbee88684.png)

**Comment by Hi-Angel** [comment]
> @ankurdave hi. I seem to have this issue. I'm not sure if I need to be added to a list, or if I am not following a branching strategy, but I get this issue.
> ![image](https://user-images.githubusercontent.com/57162749/97595469-b6c2a180-19d1-11eb-9a70-607fbee88684.png)

Well, if you could push to repository of other people, that would be a big security hole ☺ You gotta fork the repo, and push your changes to your own fork. Then, once you're satisfied with your changes, you create a pull request from your fork/branch to ankurdave's repo.

It's also usually useful to keep upstream repo under `upstream` alias and yours under `origin` alias. To do this execute `git remote rename origin upstream` *(so now the ankurdave's repo becomes "upstream")*, and `git remote add origin https://your-fork-url`

**Comment by VizorKit** [comment]
#74

**Comment by VizorKit** [comment]
@ankurdave is this in melpa now? I do not seem to have colored variables, ensuring i installed the latest.
