### ISSUE TITLE
Don't use red color, as some mode use them to show errors

### ISSUE THREAD

**Issue by larebsyed** [ankurdave/color-identifiers-mode#59]

**Comment by alphapapa** [comment]
It might be even better to lookup the `font-lock-warning-face` and avoid using a color similar to that, rather than hard-coding red as the color to avoid.

**Comment by ankurdave** [comment]
I agree with @Hi-Angel's comments on this: colors are rather scarce, and many of them have other meanings in various contexts, so this might be a slippery slope.

However, if you want to experiment with the idea, [here's one way to achieve this change](https://github.com/ankurdave/color-identifiers-mode/commit/c0cdf64202717797191b279788f6769198ae86e4). I modified `color-identifiers:regenerate-colors`, specifically [`(cons bgcolor chosens)`](https://github.com/ankurdave/color-identifiers-mode/blob/60ae3ab0fdffe0efae7e08950d7b2a96f4ea49e2/color-identifiers-mode.el#L609). That line means each new color is maximally far from the previously chosen colors plus the background color. To get the desired behavior we just add another color to the list.

**Comment by larebsyed** [comment]
How about we make this color black list a customizable variable in which we can add color or faces to black list?

**Comment by larebsyed** [comment]
Any update? I thought we were getting there?

**Comment by ankurdave** [comment]
A pull request to that effect is welcome.

**Comment by alphapapa** [comment]
> I haven't managed to look up the value because C-h v font-lock-warning-face says that its value is `font-lock-warning-face` which doesn't make sense to me

It's a face.  Use `describe-face`, not `describe-variable`.
