### ISSUE TITLE
global-color-identifiers-mode not happening in c-mode automatically

### ISSUE THREAD

**Issue by VizorKit** [ankurdave/color-identifiers-mode#75]
I have set up color-identifiers-mode as such.

```
(use-package color-identifiers-mode
  :ensure t
  :defer t
  :config
  (add-hook 'after-init-hook 'global-color-identifiers-mode))
```
I have even tried the `:hook` property with `use-package` as such.
```
:hook ((after-init . global-color-identifiers))
```
Every time i open a c file or h file. I need to set run `M-x global-color-identifiers-mode` in order for color-identifiers to happen on the current buffer.

Any thoughts on what I'm doing incorrectly?

**Comment by Hi-Angel** [comment]
So, when I remove my `.emacs.elc` and replace `.emacs` file content with just two lines:

```
(package-initialize)
(add-hook 'after-init-hook 'global-color-identifiers-mode)
```

…and then I launch Emacs and open a C file, I see variables are highlighted correctly. Please check if it works for you too. If it is, it's probably something in your setup.

**Comment by Hi-Angel** [comment]
Please note, the color highlighting does not happen immediately, but rather on inactivity timeout. The time [by default is 5 seconds](https://github.com/ankurdave/color-identifiers-mode/blob/09684e62f0d28b22e60f3f6f50c5941549315134/color-identifiers-mode.el#L64).

**Comment by VizorKit** [comment]
I found this set up resolved the issue,
```
(use-package color-identifiers-mode
  :ensure t
  :config
  (add-hook 'c-mode-hook 'color-identifiers-mode))
```
for some reason I couldn't use `:hook` or `global-identifers-mode`
As far as the timer, what setting exactly should I have for let's say 1 second or even .1 second? @Hi-Angel

**Comment by VizorKit** [comment]
nvm. this worked.
` (setq color-identifiers:timer (run-with-idle-timer 0.2 t 'color-identifiers:refresh))

**Comment by Hi-Angel** [comment]
Glad you resolved it! If it is fine now, I think you might want to close this report.

**Comment by Hi-Angel** [comment]
FTR, I opened [a PR](https://github.com/ankurdave/color-identifiers-mode/pull/87) that should make that easier and also adds some docs in that regard.

**Comment by Hi-Angel** [comment]
FTR: I opened a discussion to decrease the delay as well to reduce possible confusion https://github.com/ankurdave/color-identifiers-mode/pull/89
