### ISSUE TITLE
When enabled, org mode buffer tangling becomes very slow

### ISSUE THREAD

**Issue by noorul** [ankurdave/color-identifiers-mode#79]
I have the following configuration 

```elisp
(use-package color-identifiers-mode
  :diminish color-identifiers-mode
  :init (add-hook 'after-init-hook 'global-color-identifiers-mode))
```

With above configuration tangling functionality from org-mode is taking a lot of time

**Comment by noorul** [comment]
No, I am not using it.

**Comment by Hi-Angel** [comment]
Can you post a reproducer please? I myself don't use org-mode, so trying to reproduce it may take some time, especially given last upstream changes in Emacs itself sped up some things, so it may not even be reproducible anymore.

**Comment by noorul** [comment]
I am not using this mode anymore. I am closing this issue as I am not able to provide a reproducible recipe.
