### ISSUE TITLE
color-identifiers-mode is very slow when hideshowvis is enabled

### ISSUE THREAD

**Issue by eyal0** [ankurdave/color-identifiers-mode#83]
I can't tell which one is the issue here.

When both hideshowvis and color-identifiers-mode are in use, `color-identifiers:refresh` becomes very slow on large files.  When hideshowvis is not loaded, `color-identifiers:refresh` is much faster (like .5 seconds versus 15 seconds).

To reproduce this, first get hideshowvis installed.  Save this [file](https://raw.githubusercontent.com/sheijk/hideshowvis/master/hideshowvis.el) into `~/emacs.d/lisp`.

In `init.el` add

```elisp
(use-package hideshowvis
  :diminish
  :load-path "~/.emacs.d/lisp"
  :bind ("M-[" . hs-toggle-hiding)
  :init (progn
          (add-hook #'prog-mode-hook (lambda () (hideshowvis-enable) (hideshowvis-symbols)))))
```

That will cause hideshowvis to open when a programming file is opened, like c++.

Now we need to open a large c++ file.  Download this [file](https://raw.githubusercontent.com/tensorflow/tensorflow/d77a240173605be29cc20d860a46b5b9575b11d2/tensorflow/lite/delegates/gpu/cl/inference_context.cc) to `~/Downloads/inference_context.cc`.

Now open that file in emacs.  Confirm that there are little minus signs in the fringe which can be clicked to shrink and expand code.

Now type `M-x color-identifiers:refresh`.  It should return in under 0.5 seconds.

Now hold page down on the keyboard until you reach the end of the file.  Once again, type `M-x color-identifiers:refresh`.  It will take noticeably longer, like 4 seconds or so.  This will be the case from now on.  Now page up all the way to the top and try again.  Now it might be even longer, like 12 seconds.

`M-x profiler-start` before the slowness and then `M-x profiler-report` after the slowness shows 99% of the cpu time in `thing-at-point`, called by `symbol-at-point` in color-identifiers.  It's not clear if that is many more calls to thing-at-point or just more time spent inside the function.  I don't know a method to count calls in elisp.

**Comment by eyal0** [comment]
Weird, I'm not seeing it now either.  I'll remember this tip and then next time that I can reproduce the slowness, I will try this.

**Comment by Hi-Angel** [comment]
So, latest master has undergone quite a lot of optimizations and cleanups. And given this problem is no longer reproducible, I'm inclined to close the report.

Please feel free to reopen if you find a way to reproduce it.

**Comment by eyal0** [comment]
I found the issue: https://github.com/sheijk/hideshowvis/issues/11  It is a hideshowvis problem, not color identifiers problem.
